// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/model/response_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 6252344056220842342),
    name: 'ResponseModel',
    lastPropertyId: const obx_int.IdUid(15, 1891970489467051978),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7781434923888294841),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1765185365898212930),
        name: 'requestId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 327941238483880056),
        name: 'statusCode',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1785590117697847469),
        name: 'body',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 4570476412155728953),
        name: 'size',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 8852059660327418858),
        name: 'isCached',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 6845735097468893073),
        name: 'error',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 3518428800766289616),
        name: 'headersJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 1891970489467051978),
        name: 'responseTimeMs',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 6252344056220842342),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      7871219635448067208,
      1353642512713215052,
      4865653772492112720,
      1754482443840694371,
      6582779969642996236,
      9194246531960346251,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ResponseModel: obx_int.EntityDefinition<ResponseModel>(
      model: _entities[0],
      toOneRelations: (ResponseModel object) => [],
      toManyRelations: (ResponseModel object) => {},
      getId: (ResponseModel object) => object.id,
      setId: (ResponseModel object, int id) {
        object.id = id;
      },
      objectToFB: (ResponseModel object, fb.Builder fbb) {
        final requestIdOffset = fbb.writeString(object.requestId);
        final bodyOffset = fbb.writeString(object.body);
        final errorOffset = object.error == null
            ? null
            : fbb.writeString(object.error!);
        final headersJsonOffset = fbb.writeString(object.headersJson);
        fbb.startTable(16);
        fbb.addInt64(0, object.id);
        fbb.addOffset(7, requestIdOffset);
        fbb.addInt64(8, object.statusCode);
        fbb.addOffset(9, bodyOffset);
        fbb.addInt64(10, object.size);
        fbb.addBool(11, object.isCached);
        fbb.addOffset(12, errorOffset);
        fbb.addOffset(13, headersJsonOffset);
        fbb.addInt64(14, object.responseTimeMs);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final requestIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final statusCodeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final headersJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 30, '');
        final bodyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 22, '');
        final sizeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final responseTimeMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          32,
          0,
        );
        final isCachedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          26,
          false,
        );
        final errorParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 28);
        final object = ResponseModel(
          requestId: requestIdParam,
          statusCode: statusCodeParam,
          headersJson: headersJsonParam,
          body: bodyParam,
          size: sizeParam,
          responseTimeMs: responseTimeMsParam,
          isCached: isCachedParam,
          error: errorParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ResponseModel] entity fields to define ObjectBox queries.
class ResponseModel_ {
  /// See [ResponseModel.id].
  static final id = obx.QueryIntegerProperty<ResponseModel>(
    _entities[0].properties[0],
  );

  /// See [ResponseModel.requestId].
  static final requestId = obx.QueryStringProperty<ResponseModel>(
    _entities[0].properties[1],
  );

  /// See [ResponseModel.statusCode].
  static final statusCode = obx.QueryIntegerProperty<ResponseModel>(
    _entities[0].properties[2],
  );

  /// See [ResponseModel.body].
  static final body = obx.QueryStringProperty<ResponseModel>(
    _entities[0].properties[3],
  );

  /// See [ResponseModel.size].
  static final size = obx.QueryIntegerProperty<ResponseModel>(
    _entities[0].properties[4],
  );

  /// See [ResponseModel.isCached].
  static final isCached = obx.QueryBooleanProperty<ResponseModel>(
    _entities[0].properties[5],
  );

  /// See [ResponseModel.error].
  static final error = obx.QueryStringProperty<ResponseModel>(
    _entities[0].properties[6],
  );

  /// See [ResponseModel.headersJson].
  static final headersJson = obx.QueryStringProperty<ResponseModel>(
    _entities[0].properties[7],
  );

  /// See [ResponseModel.responseTimeMs].
  static final responseTimeMs = obx.QueryIntegerProperty<ResponseModel>(
    _entities[0].properties[8],
  );
}
